import React, { useRef, useState } from 'react';
import { Button, CircularProgress } from '@mui/material';
import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';
import type { ComponentBase } from '../types/api';

interface ComponentEntry {
  label: string;
  component: ComponentBase | null;
}

interface ExportBuildPDFProps {
  components: ComponentEntry[];
  totalPrice: number;
  disabled?: boolean;
}

export const ExportBuildPDF: React.FC<ExportBuildPDFProps> = ({
  components,
  totalPrice,
  disabled,
}) => {
  const [loading, setLoading] = useState(false);
  const canvasRef = useRef<HTMLDivElement>(null);

  const handleExport = async () => {
    setLoading(true);
    try {
      const { default: jsPDF } = await import('jspdf');
      const { default: html2canvas } = await import('html2canvas');

      const container = document.createElement('div');
      container.style.cssText =
        'position:fixed;left:-9999px;top:0;width:700px;padding:40px;background:#1a1a1a;color:#f3f4f6;font-family:Inter,Arial,sans-serif;';

      const date = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });

      let html = `
        <div style="border-bottom:3px solid #f97316;padding-bottom:16px;margin-bottom:24px;">
          <h1 style="margin:0;font-size:28px;color:#f97316;">PC Builder</h1>
          <p style="margin:4px 0 0;font-size:13px;color:#9ca3af;">Build Summary &mdash; ${date}</p>
        </div>
        <table style="width:100%;border-collapse:collapse;">
          <thead>
            <tr style="border-bottom:1px solid #333;">
              <th style="text-align:left;padding:10px 8px;font-size:13px;color:#9ca3af;font-weight:600;">Component</th>
              <th style="text-align:left;padding:10px 8px;font-size:13px;color:#9ca3af;font-weight:600;">Selection</th>
              <th style="text-align:right;padding:10px 8px;font-size:13px;color:#9ca3af;font-weight:600;">Price</th>
            </tr>
          </thead>
          <tbody>
      `;

      for (const entry of components) {
        const name = entry.component?.name ?? '—';
        const price = entry.component
          ? `${Number(entry.component.price || 0).toFixed(2)} zł`
          : '—';
        const nameColor = entry.component ? '#f3f4f6' : '#555';
        const priceColor = entry.component ? '#fdba74' : '#555';

        html += `
          <tr style="border-bottom:1px solid #2a2a2a;">
            <td style="padding:10px 8px;font-size:13px;font-weight:600;color:#9ca3af;white-space:nowrap;">${entry.label}</td>
            <td style="padding:10px 8px;font-size:13px;color:${nameColor};max-width:320px;overflow:hidden;text-overflow:ellipsis;">${name}</td>
            <td style="padding:10px 8px;font-size:13px;color:${priceColor};text-align:right;white-space:nowrap;font-weight:600;">${price}</td>
          </tr>
        `;
      }

      const formattedTotal = Number(totalPrice || 0).toLocaleString(undefined, {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      });

      html += `
          </tbody>
        </table>
        <div style="margin-top:24px;padding-top:16px;border-top:2px solid #f97316;display:flex;justify-content:space-between;align-items:baseline;">
          <span style="font-size:18px;font-weight:700;color:#f3f4f6;">Total Price</span>
          <span style="font-size:26px;font-weight:800;color:#f97316;">${formattedTotal} zł</span>
        </div>
        <p style="margin-top:32px;font-size:11px;color:#555;text-align:center;">
          Generated by PC Builder
        </p>
      `;

      container.innerHTML = html;
      document.body.appendChild(container);

      const canvas = await html2canvas(container, {
        backgroundColor: '#1a1a1a',
        scale: 2,
      });

      document.body.removeChild(container);

      const imgData = canvas.toDataURL('image/png');
      const imgWidth = 190;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      const pdf = new jsPDF('p', 'mm', 'a4');
      pdf.addImage(imgData, 'PNG', 10, 10, imgWidth, imgHeight);
      pdf.save('pc-build-summary.pdf');
    } catch (err) {
      console.error('PDF export failed:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <div ref={canvasRef} style={{ display: 'none' }} />
      <Button
        fullWidth
        variant="outlined"
        color="primary"
        onClick={handleExport}
        disabled={disabled || loading}
        startIcon={loading ? <CircularProgress size={18} /> : <PictureAsPdfIcon />}
        sx={{
          fontWeight: 600,
          borderColor: 'primary.main',
          '&:hover': {
            borderColor: 'primary.light',
            backgroundColor: 'rgba(249, 115, 22, 0.08)',
          },
        }}
      >
        {loading ? 'Generating...' : 'Export to PDF'}
      </Button>
    </>
  );
};

export default ExportBuildPDF;
